version: "3.9"

services:
  # Reverse proxy service
  nginx:
    image: nginx:alpine
    container_name: hackout-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx:rw
      - ./cache:/var/cache/nginx:rw
    depends_on:
      - client
      - server
    restart: unless-stopped
    networks:
      - hackout-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: hackout-client
    restart: unless-stopped
    networks:
      - hackout-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production

  # Node.js backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hackout-server
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - hackout-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs

  # Valkey service
  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - hackout-network

  # Qdrant service
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    restart: unless-stopped
    networks:
      - hackout-network

networks:
  hackout-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  uploads:
  logs:
